# Generated by Django 6.1.1 on 2026-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
    ]
