# Generated by Django 6.1.1 on 2026-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_blog_reading_time_blog_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
    ]
