# Generated by Django 6.1.1 on 2026-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_remove_blog_reading_time_remove_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background_color',
            field=models.CharField(default='#b22222', max_length=20),
            preserve_default=False,
        ),
    ]
