# Generated by Django 6.1.1 on 2026-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_dispatchrequest_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(upload_to='portfolio_mages/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipment Portfolio',
                'verbose_name_plural': 'Equipment Portfolioes',
            },
        ),
    ]
