# Generated by Django 6.1.1 on 2026-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.CharField(default='5 MIN READ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='5 MIN READ', max_length=100),
            preserve_default=False,
        ),
    ]
