# Generated by Django 6.1.1 on 2026-10-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_blog_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='background_color',
        ),
    ]
